// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/Path.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ProtoPath extends Message {

  public static final List<ProtoCoordinate> DEFAULT_COORDINATES = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<ProtoCoordinate> coordinates;

  private ProtoPath(Builder builder) {
    super(builder);
    this.coordinates = immutableCopyOf(builder.coordinates);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoPath)) return false;
    return equals(coordinates, ((ProtoPath) other).coordinates);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = coordinates != null ? coordinates.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ProtoPath> {

    public List<ProtoCoordinate> coordinates;

    public Builder() {
    }

    public Builder(ProtoPath message) {
      super(message);
      if (message == null) return;
      this.coordinates = copyOf(message.coordinates);
    }

    public Builder coordinates(List<ProtoCoordinate> coordinates) {
      this.coordinates = coordinates;
      return this;
    }

    @Override
    public ProtoPath build() {
      return new ProtoPath(this);
    }
  }
}
