// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/matthewkuo92/Desktop/proto/ProtoRoutes.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ProtoRoutes extends Message {

  public static final List<ProtoRoute> DEFAULT_ROUTES = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<ProtoRoute> routes;

  private ProtoRoutes(Builder builder) {
    super(builder);
    this.routes = immutableCopyOf(builder.routes);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoRoutes)) return false;
    return equals(routes, ((ProtoRoutes) other).routes);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = routes != null ? routes.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ProtoRoutes> {

    public List<ProtoRoute> routes;

    public Builder() {
    }

    public Builder(ProtoRoutes message) {
      super(message);
      if (message == null) return;
      this.routes = copyOf(message.routes);
    }

    public Builder routes(List<ProtoRoute> routes) {
      this.routes = routes;
      return this;
    }

    @Override
    public ProtoRoutes build() {
      return new ProtoRoutes(this);
    }
  }
}
