// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/RouteData.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.PACKED;

public final class ProtoRouteData extends Message {

  public static final List<Integer> DEFAULT_STOPS0 = Collections.emptyList();
  public static final List<Integer> DEFAULT_STOPS1 = Collections.emptyList();

  @ProtoField(tag = 1, type = INT32, label = PACKED)
  public final List<Integer> stops0;

  @ProtoField(tag = 2, type = INT32, label = PACKED)
  public final List<Integer> stops1;

  private ProtoRouteData(Builder builder) {
    super(builder);
    this.stops0 = immutableCopyOf(builder.stops0);
    this.stops1 = immutableCopyOf(builder.stops1);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoRouteData)) return false;
    ProtoRouteData o = (ProtoRouteData) other;
    return equals(stops0, o.stops0)
        && equals(stops1, o.stops1);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = stops0 != null ? stops0.hashCode() : 0;
      result = result * 37 + (stops1 != null ? stops1.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ProtoRouteData> {

    public List<Integer> stops0;
    public List<Integer> stops1;

    public Builder() {
    }

    public Builder(ProtoRouteData message) {
      super(message);
      if (message == null) return;
      this.stops0 = copyOf(message.stops0);
      this.stops1 = copyOf(message.stops1);
    }

    public Builder stops0(List<Integer> stops0) {
      this.stops0 = stops0;
      return this;
    }

    public Builder stops1(List<Integer> stops1) {
      this.stops1 = stops1;
      return this;
    }

    @Override
    public ProtoRouteData build() {
      return new ProtoRouteData(this);
    }
  }
}
