// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/Stops.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ProtoStops extends Message {

  public static final List<ProtoStop> DEFAULT_STOPS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<ProtoStop> stops;

  public ProtoStops(List<ProtoStop> stops) {
    this.stops = immutableCopyOf(stops);
  }

  private ProtoStops(Builder builder) {
    this(builder.stops);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoStops)) return false;
    return equals(stops, ((ProtoStops) other).stops);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = stops != null ? stops.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<ProtoStops> {

    public List<ProtoStop> stops;

    public Builder() {
    }

    public Builder(ProtoStops message) {
      super(message);
      if (message == null) return;
      this.stops = copyOf(message.stops);
    }

    public Builder stops(List<ProtoStop> stops) {
      this.stops = checkForNulls(stops);
      return this;
    }

    @Override
    public ProtoStops build() {
      return new ProtoStops(this);
    }
  }
}
