// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/Coordinate.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.FLOAT;

public final class ProtoCoordinate extends Message {

  public static final Float DEFAULT_LATITUDE = 0F;
  public static final Float DEFAULT_LONGITUDE = 0F;

  @ProtoField(tag = 1, type = FLOAT)
  public final Float latitude;

  @ProtoField(tag = 2, type = FLOAT)
  public final Float longitude;

  private ProtoCoordinate(Builder builder) {
    super(builder);
    this.latitude = builder.latitude;
    this.longitude = builder.longitude;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoCoordinate)) return false;
    ProtoCoordinate o = (ProtoCoordinate) other;
    return equals(latitude, o.latitude)
        && equals(longitude, o.longitude);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = latitude != null ? latitude.hashCode() : 0;
      result = result * 37 + (longitude != null ? longitude.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ProtoCoordinate> {

    public Float latitude;
    public Float longitude;

    public Builder() {
    }

    public Builder(ProtoCoordinate message) {
      super(message);
      if (message == null) return;
      this.latitude = message.latitude;
      this.longitude = message.longitude;
    }

    public Builder latitude(Float latitude) {
      this.latitude = latitude;
      return this;
    }

    public Builder longitude(Float longitude) {
      this.longitude = longitude;
      return this;
    }

    @Override
    public ProtoCoordinate build() {
      return new ProtoCoordinate(this);
    }
  }
}
