// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/Shape.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ProtoShape extends Message {

  public static final List<ProtoPath> DEFAULT_PATH = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<ProtoPath> path;

  public ProtoShape(List<ProtoPath> path) {
    this.path = immutableCopyOf(path);
  }

  private ProtoShape(Builder builder) {
    this(builder.path);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoShape)) return false;
    return equals(path, ((ProtoShape) other).path);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = path != null ? path.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<ProtoShape> {

    public List<ProtoPath> path;

    public Builder() {
    }

    public Builder(ProtoShape message) {
      super(message);
      if (message == null) return;
      this.path = copyOf(message.path);
    }

    public Builder path(List<ProtoPath> path) {
      this.path = checkForNulls(path);
      return this;
    }

    @Override
    public ProtoShape build() {
      return new ProtoShape(this);
    }
  }
}
