// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos/Stop.proto
package com.mattkuo.wheredatbus.protobuff;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class ProtoStop extends Message {

  public static final Integer DEFAULT_STOP_CODE = 0;
  public static final String DEFAULT_STOP_NAME = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer stop_code;

  @ProtoField(tag = 2, type = STRING)
  public final String stop_name;

  @ProtoField(tag = 3)
  public final ProtoCoordinate coordinate;

  private ProtoStop(Builder builder) {
    super(builder);
    this.stop_code = builder.stop_code;
    this.stop_name = builder.stop_name;
    this.coordinate = builder.coordinate;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ProtoStop)) return false;
    ProtoStop o = (ProtoStop) other;
    return equals(stop_code, o.stop_code)
        && equals(stop_name, o.stop_name)
        && equals(coordinate, o.coordinate);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = stop_code != null ? stop_code.hashCode() : 0;
      result = result * 37 + (stop_name != null ? stop_name.hashCode() : 0);
      result = result * 37 + (coordinate != null ? coordinate.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ProtoStop> {

    public Integer stop_code;
    public String stop_name;
    public ProtoCoordinate coordinate;

    public Builder() {
    }

    public Builder(ProtoStop message) {
      super(message);
      if (message == null) return;
      this.stop_code = message.stop_code;
      this.stop_name = message.stop_name;
      this.coordinate = message.coordinate;
    }

    public Builder stop_code(Integer stop_code) {
      this.stop_code = stop_code;
      return this;
    }

    public Builder stop_name(String stop_name) {
      this.stop_name = stop_name;
      return this;
    }

    public Builder coordinate(ProtoCoordinate coordinate) {
      this.coordinate = coordinate;
      return this;
    }

    @Override
    public ProtoStop build() {
      return new ProtoStop(this);
    }
  }
}
